name: vrtguide
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.1+3
  dio: ^3.0.8
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  flare_flutter: ^1.8.3
  shared_preferences: ^0.5.6
  camera: ^0.5.7+3
  path_provider: ^0.5.0
  url_launcher: ^5.4.1
  expandable: ^4.0.2
  timeline_list: ^0.0.5
  fuzzy: ^0.2.0+8
  google_sign_in: ^4.1.1
  dots_indicator: ^1.1.0
  youtube_api: ^0.7.2
  google_maps_flutter: ^0.5.21+15
  flutter_tts: ^0.8.6
  flutter_dialogflow: ^0.1.2
  speech_recognition: ^0.3.0+1
  speech_to_text: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/loading_pizza.flr
    - lib/assets/camera.flr
    - lib/assets/beach_portrait.jpg
    - lib/assets/wildlife.jpg
    - lib/assets/landscape_default.png
    - lib/assets/google-logo.png
    - lib/assets/fb.png
    - lib/assets/tw.png
    - lib/assets/insta.png
    - lib/assets/cat_adventure.jpg
    - lib/assets/cat_beaches.jpg
    - lib/assets/cat_history.jpg
    - lib/assets/cat_nature.jpg
    - lib/assets/cat_pilgrimage.jpg
    - lib/assets/cat_wildlife.jpg
    - lib/assets/blog_images/adventure1.jpg
    - lib/assets/blog_images/beach1.jpg
    - lib/assets/blog_images/beach2.jpg
    - lib/assets/blog_images/beach3.jpg
    - lib/assets/blog_images/beach4.jpg
    - lib/assets/blog_images/beach5.jpg
    - lib/assets/blog_images/beach6.jpg
    - lib/assets/blog_images/diving1.jpg
    - lib/assets/blog_images/diving2.jpg
    - lib/assets/blog_images/forest1.jpg
    - lib/assets/blog_images/forest2.jpg
    - lib/assets/backgroundFirstPage.jpg
    - lib/assets/ola.png
    - lib/assets/uber.png
    - lib/assets/oyo.png
    - lib/assets/trivago.png
    - lib/assets/credentials.json
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
