INSERT INTO `landmark_tags` (lid, tag)
VALUES (1, 'history'),
(2, 'history'),
(2,'pilgrimage'),
(3, 'history'),
(3,'nature'),
(4, 'adventure'),
(4,'pilgrimage'),
(5, 'history'),
(5,'pilgrimage'),
(6, 'history'),
(6,'pilgrimage'),
(7,'history'),
(7,'pilgrimage'),
(7,'adventure'),
(8,'nature'),
(8,'wildlife'),
(9,'beaches'),
(10,'beaches'),
(11,'beaches'),
(12,'beaches'),
(13,'nature'),
(13,'wildlife'),
(14,'nature'),
(14,'wildlife'),
(15,'nature'),
(15,'wildlife'),
(16,'nature'),
(17,'adventure'),
(17,'nature'),
(18,'nature')
(18,'history',
(19, 'history'),
(19,'nature'),
(20, 'history'),
(20,'pilgrimage'),
(21, 'history'),
(21,'pilgrimage');